from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_tic_tac_toe.models.base_model import Model
from openapi_tic_tac_toe import util


class GamesGameIdPutRequest(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, px=None, py=None):  # noqa: E501
        """GamesGameIdPutRequest - a model defined in OpenAPI

        :param px: The px of this GamesGameIdPutRequest.  # noqa: E501
        :type px: int
        :param py: The py of this GamesGameIdPutRequest.  # noqa: E501
        :type py: int
        """
        self.openapi_types = {
            'px': int,
            'py': int
        }

        self.attribute_map = {
            'px': 'px',
            'py': 'py'
        }

        self._px = px
        self._py = py

    @classmethod
    def from_dict(cls, dikt) -> 'GamesGameIdPutRequest':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The _games__game_id__put_request of this GamesGameIdPutRequest.  # noqa: E501
        :rtype: GamesGameIdPutRequest
        """
        return util.deserialize_model(dikt, cls)

    @property
    def px(self) -> int:
        """Gets the px of this GamesGameIdPutRequest.

        Dot's X position.  # noqa: E501

        :return: The px of this GamesGameIdPutRequest.
        :rtype: int
        """
        return self._px

    @px.setter
    def px(self, px: int):
        """Sets the px of this GamesGameIdPutRequest.

        Dot's X position.  # noqa: E501

        :param px: The px of this GamesGameIdPutRequest.
        :type px: int
        """
        if px is None:
            raise ValueError("Invalid value for `px`, must not be `None`")  # noqa: E501
        if px is not None and px > 3:  # noqa: E501
            raise ValueError("Invalid value for `px`, must be a value less than or equal to `3`")  # noqa: E501
        if px is not None and px < 1:  # noqa: E501
            raise ValueError("Invalid value for `px`, must be a value greater than or equal to `1`")  # noqa: E501

        self._px = px

    @property
    def py(self) -> int:
        """Gets the py of this GamesGameIdPutRequest.

        Dot's Y position.  # noqa: E501

        :return: The py of this GamesGameIdPutRequest.
        :rtype: int
        """
        return self._py

    @py.setter
    def py(self, py: int):
        """Sets the py of this GamesGameIdPutRequest.

        Dot's Y position.  # noqa: E501

        :param py: The py of this GamesGameIdPutRequest.
        :type py: int
        """
        if py is None:
            raise ValueError("Invalid value for `py`, must not be `None`")  # noqa: E501
        if py is not None and py > 3:  # noqa: E501
            raise ValueError("Invalid value for `py`, must be a value less than or equal to `3`")  # noqa: E501
        if py is not None and py < 1:  # noqa: E501
            raise ValueError("Invalid value for `py`, must be a value greater than or equal to `1`")  # noqa: E501

        self._py = py
